/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRide' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'approveRide' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkGhostChannel' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'closeGhostChannel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'createGhostChannel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'createRideRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Text, IDL.Text],
      [],
    ),
  'createSession' : IDL.Func([IDL.Text], [IDL.Text], []),
  'endSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGhostMessages' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Int))],
      ['query'],
    ),
  'getReputation' : IDL.Func([IDL.Text], [IDL.Text, IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'heartbeatQuery' : IDL.Func([], [], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGhostChannel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'listAvailableRides' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Text,
            IDL.Text,
            IDL.Bool,
            IDL.Text,
            IDL.Nat,
            IDL.Nat,
            IDL.Nat,
            IDL.Text,
          )
        ),
      ],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendGhostMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitRating' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Bool], []),
  'updateRideStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRide' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'approveRide' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkGhostChannel' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'closeGhostChannel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'createGhostChannel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'createRideRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Text, IDL.Text],
        [],
      ),
    'createSession' : IDL.Func([IDL.Text], [IDL.Text], []),
    'endSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGhostMessages' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Int))],
        ['query'],
      ),
    'getReputation' : IDL.Func([IDL.Text], [IDL.Text, IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'heartbeatQuery' : IDL.Func([], [], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGhostChannel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'listAvailableRides' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Text,
              IDL.Bool,
              IDL.Text,
              IDL.Nat,
              IDL.Nat,
              IDL.Nat,
              IDL.Text,
            )
          ),
        ],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendGhostMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'submitRating' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Bool], []),
    'updateRideStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };